### ISSUE TITLE
How do I make it work with ruby on rails backend?

### ISSUE THREAD

**Issue by sainath13** [fullstackreact/react-native-oauth#133]
I might be asking a rookie question but I just can't understand the whole flow of the oauth login with facebook.  Please provide some insights.

**Comment by Amnesthesia** [comment]
@sainath13 this is how I've set it up with Rails:

1. User authenticates in app, and retrieves an Access Token
2. POST access token, user ID and provider to my /users endpoint
3. Back-end attempts to fetch the user for that access token (using Koala gem)
4. If a user is retrieved, it is either created or fetched from the database, and returned
5. Otherwise 401

From there you can do your own token authentication — I use JWT but it may not be the best option. Up to you.

**Comment by sainath13** [comment]
@Amnesthesia Thank you so much. I use devise gem. I was not able to understand the difference between server side oauth and client side oauth.
