### ISSUE TITLE
Andorid : You are not logged in. Please log in and try again but iOS works fine.

### ISSUE THREAD

**Issue by ayberkanilatsiz** [fullstackreact/react-native-oauth#202]
Hey,

I did all config in the readme. iOS works fine but Android gets an error.

![screen shot 2018-04-06 at 11 08 41](https://user-images.githubusercontent.com/7476653/38409663-ea86752a-398a-11e8-9b2a-d9eeb3847722.png)

These my facebook android settings

![screen shot 2018-04-06 at 11 09 45](https://user-images.githubusercontent.com/7476653/38409729-2bcf8986-398b-11e8-9987-1dd4d3950c45.png)

**Comment by SoldierCorp** [comment]
Apparently no one is going to help, I have the same error but since this issue it's been open from April, I don't think the owner is still working on this.

**Comment by ayberkanilatsiz** [comment]
@SoldierCorp don't use this one. I did not find any solution. 

Use https://github.com/facebook/react-native-fbsdk

**Comment by iyogeshjoshi** [comment]
I think the issue is the module is maintaining session from last login and hence giving you are logged in error. I have found this same issue in other libraries too, what we need to do is `logout`before you use `login` call. You need to `deauthorize()` before you can `authorize()`. check this [issue](https://github.com/fullstackreact/react-native-oauth/issues/93#issuecomment-312813938) .

**Comment by muhammadfariscom** [comment]
There's a workaround for this problem by disabling the "enforce HTTPS" and change the  redirect URL to http://localhost/facebook

source: ChrisEelmaa https://github.com/sahat/satellizer/issues/742#issuecomment-416192632

But if we look at the Facebook Developer page, we will need to use HTTPS by October 6, 2018.
